language: python

python:
  - 3.6

before_install:
  - pip install codecov coverage

install:
  -

script:
  - PYTHONPATH=. coverage run -m unittest discover -v -s testhelpers/tests
  - coverage run setup.py -q install
  - coverage combine -a
  - coverage report

after_success:
  - codecov
